# Generated by Django 5.2 on 2025-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_delete_day_alter_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, default='Xozirda biriktirilgan gurux mavjud emas', null=True, related_name='get_course', to='user_auth.course'),
        ),
    ]
