# Generated by Django 5.2 on 2025-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='get_course', to='user_auth.course'),
        ),
    ]
