# Generated by Django 5.2 on 2025-04-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0004_alter_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('arribal_time', models.DateTimeField(blank=True, null=True)),
                ('izox', models.CharField(blank=True, max_length=150, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.groupstudent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.student')),
            ],
            options={
                'unique_together': {('student', 'group', 'date')},
            },
        ),
    ]
